version: '3.8'

# Services
services:

  # backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend
    ports:
      - "8080:8080"

  # frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"


